# config.yml
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
media_folder: 'src/uploads'
public_folder: "/uploads"
collections:
  - label: "Sections"
    name: "sections"
    editor:
      preview: false
    files:
      - label: "Home"
        name: "home"
        file: "/src/_data/home.json"
        fields:
          - {label: 'Title', name: 'title', widget: 'string' }
          - label: Intro
            name: intro
            widget: object
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - {label: 'Description', name: 'description', widget: 'markdown' }
          - label: Projects
            name: projects
            widget: list
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - {label: 'Description', name: 'description', widget: 'text' }
              - { label: 'Link', name: 'link', widget: 'string' }
          - label: Hire
            name: hire
            widget: object
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - {label: 'Description', name: 'description', widget: 'markdown' }
              - label: Link
                name: link
                widget: object
                fields:
                  - { label: 'Text', name: 'text', widget: 'string' }
                  - { label: 'URL', name: 'url', widget: 'string' }
          - label: Join
            name: join
            widget: object
            fields:
              - { label: 'Title', name: 'title', widget: 'string' }
              - {label: 'Description', name: 'description', widget: 'markdown' }
  - name: 'pipeline'
    label: 'Activities'
    folder: 'src/pipeline/'
    create: true
    editor:
      preview: true
    fields:
      - { name: 'layout', widget: 'hidden', default: 'layouts/post.njk' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Introduction', name: 'intro', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', dateFormat: 'Do MMM YYYY', timeFormat: false }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Image alt text', name: 'image_alt', widget: 'string'}
      - { label: 'Description', name: 'body', widget: 'markdown'}
      - { label: 'Document link', name: 'ideas_link', widget: 'string'}
  - name: 'tips'
    label: 'Tips'
    folder: 'src/tips/'
    create: true
    editor:
      preview: true
    fields:
      - { name: 'layout', widget: 'hidden', default: 'layouts/post.njk' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', dateFormat: 'Do MMM YYYY', timeFormat: false }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Image alt text', name: 'image_alt', widget: 'string'}
      - { label: 'Description', name: 'body', widget: 'markdown'}
  - name: 'posts'
    label: 'Our thinking'
    folder: 'src/posts/'
    create: true
    editor:
      preview: true
    fields:
      - { name: 'layout', widget: 'hidden', default: 'layouts/post.njk' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Date', name: 'date', widget: 'datetime', dateFormat: 'Do MMM YYYY', timeFormat: false }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Image alt text', name: 'image_alt', widget: 'string'}
      - { label: 'Description', name: 'body', widget: 'markdown'}
